name: CI
on:
  push:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: golint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
          args: --timeout 5m
  verify:
    name: verify
    runs-on: ubuntu-22.04
    env:
      GOPATH: ${{ github.workspace }}
      WORKSPACE: ${{ github.workspace }}/src/github.com/kosmos-io/netdoctor
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORKSPACE }}
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
  build:
    name: build
    needs: verify
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Compile
        run: make netctl

